#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko.becker@kde.org)
#
Name     : ksanecore
Version  : 22.08.1
Release  : 2
URL      : https://download.kde.org/stable/release-service/22.08.1/src/ksanecore-22.08.1.tar.xz
Source0  : https://download.kde.org/stable/release-service/22.08.1/src/ksanecore-22.08.1.tar.xz
Source1  : https://download.kde.org/stable/release-service/22.08.1/src/ksanecore-22.08.1.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause CC0-1.0 LGPL-2.1 LGPL-3.0
Requires: ksanecore-lib = %{version}-%{release}
Requires: ksanecore-license = %{version}-%{release}
Requires: ksanecore-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : ki18n-dev
BuildRequires : sane-backends-dev

%description
<!--
SPDX-License-Identifier: CC0-1.0
-->
# KSaneCore
## Introduction
KSaneCore is a library that provides a Qt interface for the SANE library for scanner hardware.

%package dev
Summary: dev components for the ksanecore package.
Group: Development
Requires: ksanecore-lib = %{version}-%{release}
Provides: ksanecore-devel = %{version}-%{release}
Requires: ksanecore = %{version}-%{release}

%description dev
dev components for the ksanecore package.


%package lib
Summary: lib components for the ksanecore package.
Group: Libraries
Requires: ksanecore-license = %{version}-%{release}

%description lib
lib components for the ksanecore package.


%package license
Summary: license components for the ksanecore package.
Group: Default

%description license
license components for the ksanecore package.


%package locales
Summary: locales components for the ksanecore package.
Group: Default

%description locales
locales components for the ksanecore package.


%prep
%setup -q -n ksanecore-22.08.1
cd %{_builddir}/ksanecore-22.08.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1662781991
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1662781991
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ksanecore
cp %{_builddir}/ksanecore-%{version}/LICENSES/BSD-2-Clause.txt %{buildroot}/usr/share/package-licenses/ksanecore/48425c0d29eec28e01be25cae932f6dce8e4e278
cp %{_builddir}/ksanecore-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/ksanecore/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
cp %{_builddir}/ksanecore-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/ksanecore/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
cp %{_builddir}/ksanecore-%{version}/LICENSES/LGPL-2.1-only.txt %{buildroot}/usr/share/package-licenses/ksanecore/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567
cp %{_builddir}/ksanecore-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/ksanecore/b9c8ec07abddb6bfbe08cb87aa8f68c2c2a1152f
cp %{_builddir}/ksanecore-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/ksanecore/e458941548e0864907e654fa2e192844ae90fc32
cp %{_builddir}/ksanecore-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/ksanecore/e458941548e0864907e654fa2e192844ae90fc32
pushd clr-build
%make_install
popd
%find_lang ksanecore

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/KSaneCore/DeviceInformation
/usr/include/KSaneCore/Interface
/usr/include/KSaneCore/Option
/usr/include/KSaneCore/deviceinformation.h
/usr/include/KSaneCore/interface.h
/usr/include/KSaneCore/ksanecore_export.h
/usr/include/KSaneCore/ksanecore_version.h
/usr/include/KSaneCore/option.h
/usr/lib64/cmake/KSaneCore/KSaneCoreConfig.cmake
/usr/lib64/cmake/KSaneCore/KSaneCoreConfigVersion.cmake
/usr/lib64/cmake/KSaneCore/KSaneCoreTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KSaneCore/KSaneCoreTargets.cmake
/usr/lib64/libKSaneCore.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKSaneCore.so.1
/usr/lib64/libKSaneCore.so.22.08.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ksanecore/48425c0d29eec28e01be25cae932f6dce8e4e278
/usr/share/package-licenses/ksanecore/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567
/usr/share/package-licenses/ksanecore/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/ksanecore/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/ksanecore/b9c8ec07abddb6bfbe08cb87aa8f68c2c2a1152f
/usr/share/package-licenses/ksanecore/e458941548e0864907e654fa2e192844ae90fc32

%files locales -f ksanecore.lang
%defattr(-,root,root,-)

